# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d5ef35ee82a7aae1fee609f33e4effc"
name = "Multi serial numbers"
application_url = "https://saddle-serial-numbers.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,read_order_edits,read_orders,read_products,write_order_edits,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://saddle-serial-numbers.onrender.com/api/auth",
  "https://saddle-serial-numbers.onrender.com/auth/callback"
]
